version: "3"

services:
  webserver1:
    image: php:7.4-apache
    hostname: webserver1
    networks:
      - my_network
    ports:
      - "7001:80"
      - "7021:22"
    depends_on:
      - database

  webserver2:
    image: php:7.4-apache
    hostname: webserver2
    networks:
      - my_network
    ports:
      - "7002:80"
      - "7022:22"
    depends_on:
      - database

  webserver3:
    image: php:7.4-apache
    hostname: webserver3
    networks:
      - my_network
    ports:
      - "7003:80"
      - "7023:22"
    depends_on:
      - database

  database:
    image: mariadb
    hostname: database
    networks:
      - my_network
    ports:
      - "3306:3306"
    environment:
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: lampp-haproxy
      MYSQL_USER: user
      MYSQL_PASSWORD: password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    hostname: phpmyadmin
    networks:
      - my_network
    ports:
      - "7007:80"
    environment:
    environment:
      PMA_HOST: database
      #PMA_USER: user
      #PMA_ROOT_PASSWORD: password
      #PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - database

  haproxy:
    image: haproxy:latest
    hostname: haproxy
    networks:
      - my_network
    ports:
      - "7000:80"
    depends_on:
      - webserver1
      - webserver2
      - webserver3
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

networks:
  my_network:
    driver: bridge
